baseurl = "/"
languageCode = "pt-br"
title = "7do2"
[permalinks]
  post = "/:title"
  # Nome Disqus
  disqusShortname = "7do2"
[staticman]
  endpoint = "https://api.staticman.net/v2/entry/"
  username = "lucassites"
  repository = "Hugo-sites"
  branch = "master"
