baseurl = "/"
languageCode = "pt-br"
title = "7do2"
[permalinks]
  post = "/:title"
  # Nome Disqus
  disqusShortname = "7do2"
# Add the following new Table somewhere under the params table
  [params.staticman]
  endpoint = "https://api.staticman.net/v2/entry"
  username = "7do2"
  repository = "Hugo-sites"
  branch = "master"
