baseurl = "/"
languageCode = "pt-br"
title = "7do2"
[permalinks]
  post = "/:title"
  # Nome Disqus
  disqusShortname = "7do2"
  [[headers]]
  for = "*.png" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
