baseurl = "/"
languageCode = "pt-br"
title = "7do2"
[permalinks]
post = "/:title"
  # Nome Disqus
  disqusShortname = "7do2"
  enableRobotsTXT = true
  [params]
description = "O blog que da uma luz para as suas finanças pessoais, com boas dicas e materiais completos para você!"
keywords = "Economia, finanças pessoais, Educacao financeira, investimentos inteligentes"
height = "100%
width = "100%"
[taxonomies]
author = "autores"
category = "categorias"
tag = "tags"
