baseurl = "/"
languageCode = "pt-br"
title = "7do2"
[permalinks]
  post = "/:title"
  # Nome Disqus
  disqusShortname = "7do2"
  enableRobotsTXT = true
  [params]
description = "Um blog focado em soluções SEO para outros blogs"
keywords = "Seo, Otimização"
  
