baseurl = "/"
languageCode = "pt-br"
title = "7do2"
[permalinks]
  post = "/:title"
  # Nome Disqus
  disqusShortname = "7do2"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
